#Add values for any properties you wish to change when updating connections.
#Delete any lines that you don't want to update values.
#FlexDeploy properties or plain text are allowed.
See the documentation at https://wiki.flexagon.com for more information.



######################## PROJECT_APRIL_LOOKUP_CLONE:INVOKE_FIRST ########################

#connectionType
PROJECT_APRIL_LOOKUP_CLONE:INVOKE_FIRST.connection.Connection Type=restUrl

#tlsVersion
PROJECT_APRIL_LOOKUP_CLONE:INVOKE_FIRST.connection.TLS Version=

#connectionUrl
PROJECT_APRIL_LOOKUP_CLONE:INVOKE_FIRST.connection.Connection URL=https://google.com/

#enableTwoWaySSL
PROJECT_APRIL_LOOKUP_CLONE:INVOKE_FIRST.connection.Enable two way SSL for outbound connections (Optional)=

#sslCertificateAlias
PROJECT_APRIL_LOOKUP_CLONE:INVOKE_FIRST.connection.Identity keystore alias name (Optional)=
PROJECT_APRIL_LOOKUP_CLONE:INVOKE_FIRST.agentDefinition=


######################## PROJECT_APRIL_LOOKUP_CLONE:TRIGGER_FIRST ########################
PROJECT_APRIL_LOOKUP_CLONE:TRIGGER_FIRST.agentDefinition=
